### ISSUE TITLE
Wrong numbers coming out of kat comp

### ISSUE THREAD

**Issue by dbrowneup** [TGAC/KAT#77] opened 2017-02-14 23:39 UTC
I just noticed that there is a serious discrepancy in some of the numbers between kat comp and kat hist. Using kat hist to count 1000-mers in 2 assemblies, here are the numbers I get from running jellyfish stats:

```
[dbrowne@ada8 2016.12.16_B_D3AB_K1000]$ jellyfish stats kat_hist_AB-hash.jf1000 
Unique:    152209467
Distinct:  153945908
Total:     160089032
Max_count: 199

[dbrowne@ada8 2016.12.16_B_D3AB_K1000]$ jellyfish stats kat_hist_D3-hash.jf1000 
Unique:    115884751
Distinct:  116089138
Total:     116293525
Max_count: 2
```

Now, when I run kat comp, here is what I get:

```
[dbrowne@ada8 2016.12.16_B_D3AB_K1000]$ cat kat_comp_D3AB.stats 
K-mer statistics for: 
 - Hash 1: "B_ABv5-3.fa"
 - Hash 2: "B_DDN3_BASE-3.fa"

Total K-mers in: 
 - Hash 1: 161360072
 - Hash 2: 146700181

Distinct K-mers in:
 - Hash 1: 145871207
 - Hash 2: 146130448

Total K-mers only found in:
 - Hash 1: 73239375
 - Hash 2: 59178955

Distinct K-mers only found in:
 - Hash 1: 58770418
 - Hash 2: 59029659

Shared K-mers:
 - Total shared found in hash 1: 88120697
 - Total shared found in hash 2: 87521226
 - Distinct shared K-mers: 87100789
```

The number of total and distinct 1000-mers reported by kat comp is much different than what is observed with kat hist! Moreover, the shared k-mers are off too. When I merge the two above mentioned hashes, here is what I see with jellyfish stats:

```
[dbrowne@ada8 2016.12.16_B_D3AB_K1000]$ jellyfish stats merged_1000mers.jf 
Unique:    174199349
Distinct:  222894728
Total:     276382557
Max_count: 199
```

Thus 153,945,908 + 116,089,138 - 222,894,728 distinct k-mers = 47,140,318 distinct shared k-mers.

**Comment by dbrowneup** [comment] 2017-02-14 23:41
Here are all the commands I issued:

```
bsub -J HIST_AB -L /bin/bash -W 10:00 \
    -q xlarge -n 40 -R "span[ptile=40] rusage[mem=20000]" -M 20000 \
    -o OUT_HIST_AB -cwd "/scratch/user/dbrowne/2016.12_DEC/2016.12.16_B_D3AB_K1000/" \
    "ml Westmere; ml KAT; kat hist -d -t 40 -H 165000000 -m 1000 -o kat_hist_AB B_ABv5-3.fa"

bsub -J HIST_D3 -L /bin/bash -W 10:00 \
    -q xlarge -n 40 -R "span[ptile=40] rusage[mem=20000]" -M 20000 \
    -o OUT_HIST_D3 -cwd "/scratch/user/dbrowne/2016.12_DEC/2016.12.16_B_D3AB_K1000/" \
    "ml Westmere; ml KAT; kat hist -d -t 40 -H 160000000 -m 1000 -o kat_hist_D3 B_DDN3_BASE-3.fa"

bsub -J COMP_D3AB -L /bin/bash -W 10:00 \
    -q xlarge -n 40 -R "span[ptile=40] rusage[mem=20000]" -M 20000 \
    -o OUT_COMP_D3AB -cwd "/scratch/user/dbrowne/2016.12_DEC/2016.12.16_B_D3AB_K1000/" \
    "ml Westmere; ml KAT; kat comp -v -n -m 1000 -t 40 -o kat_comp_D3AB -H 165000000 -I 160000000 B_ABv5-3.fa B_DDN3_BASE-3.fa"

bsub -J D3AB_MERGE -L /bin/bash -W 10:00 \
    -q xlarge -n 40 -R "span[ptile=40] rusage[mem=20000]" -M 20000 \
    -o OUT_D3AB_MERGE -cwd "/scratch/user/dbrowne/2016.12_DEC/2016.12.16_B_D3AB_K1000/" \
    "ml Westmere; ml Jellyfish; jellyfish merge -o merged_1000mers.jf kat_hist_AB-hash.jf1000 kat_hist_D3-hash.jf1000"
```

**Comment by maplesond** [comment] 2017-02-15 00:11
Thanks for bringing this to my attention.  I'm at a conference this week so not sure I'll have time to look at this in detail until next week.  Do you have an idea if this occurs with smaller k values?

**Comment by maplesond** [comment] 2017-02-15 00:37
I suspect there could be an issue recording all the correct settings in the hash header when dumping the hash to disk.  Can you try a direct jellfyfish comparison to kat driven directly from the fastas?

**Comment by maplesond** [comment] 2017-02-15 01:33
So I've just done a quick analysis on the Ecoli genomes, comparing jellyfish with kat hist and kat comp and everything does appear to be in order. No obvious issues with the dumped hashes...  at least for k201:

```
~/temp/kat $ jellyfish count -m201 -C -s 10000000 -o EcoliK12.fasta.jf201 EcoliK12.fasta
~/temp/kat $ jellyfish stats EcoliK12.fasta.jf201
Unique:    4569307
Distinct:  4587293
Total:     4641452
Max_count: 11
```
```
~/temp/kat $ kat hist -d -m201 -o EcoliK12.fasta.jf201.kat EcoliK12.fasta 
~/temp/kat $ jellyfish stats EcoliK12.fasta.jf201.kat-hash.jf201 
Unique:    4569307
Distinct:  4587293
Total:     4641452
Max_count: 11
```
```
~/temp/kat $ kat comp -m201 -o EcoliK12.fasta.jf201.katcomp EcoliK12.fasta EcoliK12.fasta
K-mer statistics for: 
 - Hash 1: "EcoliK12.fasta"
 - Hash 2: "EcoliK12.fasta"

Total K-mers in: 
 - Hash 1: 4641452
 - Hash 2: 4641452

Distinct K-mers in:
 - Hash 1: 4587293
 - Hash 2: 4587293

Total K-mers only found in:
 - Hash 1: 0
 - Hash 2: 0

Distinct K-mers only found in:
 - Hash 1: 0
 - Hash 2: 0

Shared K-mers:
 - Total shared found in hash 1: 4641452
 - Total shared found in hash 2: 4641452
 - Distinct shared K-mers: 4587293
```

So as far as I can tell everything is ok at smaller k values.  It would be good if you could reproduce your commands using k 201 and see if you see the same behaviour or not on your datasets.

**Comment by dbrowneup** [comment] 2017-03-18 07:56
Unfortunately, I have some bad news. I've run some more testing, this time analyzing 10-mers in raw Illumina and PacBio reads, using Jellyfish itself to generate the hashes, and then comparing them with KAT. Here are the `jellyfish stats` for the two hashes:

```
Illumina Jellyfish hash:

Unique:    0
Distinct:  524800
Total:     120772209585
Max_count: 507889652

PacBio Jellyfish hash:

Unique:    0
Distinct:  524800
Total:     17333366176
Max_count: 37251365

```

I then issued this command: `kat comp -o kat-comp_k10 -n -t 5 -m 10 Illumina/mer_counts_k10.jf PacBio/mer_counts_k10.jf` and got these results in return:

```
Kmer Analysis Toolkit (KAT) V2.1.1

Running KAT in COMP mode
------------------------

Loading hashes into memory...Loading hashes into memory...Loading hashes into memory... done.  Time taken: 0.5s

 done.  Time taken: 0.5s

 done.  Time taken: 0.5s

Comparing hashes ... done.  Time taken: 1.9s

Merging results ... done.  Time taken: 1.2s

Saving results to disk ... done.  Time taken: 0.2s

Creating plot(s) ... done.  Time taken: 3.6s

K-mer statistics for: 
 - Hash 1: "Illumina/mer_counts_k10.jf"
 - Hash 2: "PacBio/mer_counts_k10.jf"

Total K-mers in: 
 - Hash 1: 80565445538
 - Hash 2: 12087368266

Distinct K-mers in:
 - Hash 1: 353261
 - Hash 2: 371129

Total K-mers only found in:
 - Hash 1: 23130420329
 - Hash 2: 3931417305

Distinct K-mers only found in:
 - Hash 1: 103560
 - Hash 2: 121433

Shared K-mers:
 - Total shared found in hash 1: 57435025209
 - Total shared found in hash 2: 8155950961
 - Distinct shared K-mers: 249677

Distance between spectra 1 and 2 (all k-mers):
 - Manhattan distance: 18048
 - Euclidean distance: 16507.6
 - Cosine distance: 6.53905e-08
 - Canberra distance: 175.292
 - Jaccard distance: 0.0486182

Distance between spectra 1 and 2 (shared k-mers):
 - Manhattan distance: 1844
 - Euclidean distance: 810.909
 - Cosine distance: 7.93206e-08
 - Canberra distance: 128.074
 - Jaccard distance: 0.00735837

KAT COMP completed.
Total runtime: 7.5s
```

The Illumina hash should have 120 billion total k-mers and the PacBio hash should have 17 billion. There should be 524800 distinct k-mers in each hash. I tried to use `jellyfish merge` to test for common sequences, but that hit a problem: `Can't merge hash with different size (549755813888, 274877906944)`

Maybe there's a discrepancy in code between Jellyfish v2.2.4 and KAT that is causing problems? I haven't tried using KAT itself to generate the hashes for these reads.

**Comment by maplesond** [comment] 2017-03-18 09:08
Hi Dan,  Before I investigate further can you verify that you enabled the canonical kmer option in Jellyfish?  That could explain the difference in counts.

**Comment by dbrowneup** [comment] 2017-03-27 19:48
Sorry for the slow response - yes, they were all counted with canonical option enabled on Jellyfish:

```
jellyfish count -m10 -t40 -s1048576 -C -o mer_counts_k10.jf Library.SXPX.L.fq Library.SXPX.R.fq
jellyfish count -m15 -t40 -s1073741824 -C -o mer_counts_k15.jf Library.SXPX.L.fq Library.SXPX.R.fq

jellyfish count -m10 -t40 -s1048576 -C -o mer_counts_k10.jf PACBIO_Reads_6kb_Min.fasta
jellyfish count -m15 -t40 -s1073741824 -C -o mer_counts_k15.jf PACBIO_Reads_6kb_Min.fasta
```

**Comment by maplesond** [comment] 2017-03-28 08:30
Hi Dan, I'm still struggling to reproduce this.  Everything looks fine to me:

Results with k10 using jellyfish (V2.2.0... I'm a bit behind) on k-mers in the ecoli genome:
`jellyfish count -m 10 -t 2 -C -s 10000000 -o ecoli_k10 ../EcoliK12.fasta`
```
Unique:    40625
Distinct:  490389
Total:     4641643
Max_count: 284
```

Results using kat_jellyfish:
`kat_jellyfish count -m 10 -t 2 -C -s 10000000 -o ecoli_k10 ../EcoliK12.fasta`
```
Unique:    40625
Distinct:  490389
Total:     4641643
Max_count: 284
```

Results using kat_hist:
`kat hist -t 2 -m 10 -d -o ecoli_k10_kat.hist ../EcoliK12.fasta`
```
Unique:    40625
Distinct:  490389
Total:     4641643
Max_count: 284
```

Results using kat_comp:
`kat comp -t 2 -m 10 -d -o ecoli_k10_kat.comp ../EcoliK12.fasta ../EcoliK12.fasta`
```
Unique:    40625
Distinct:  490389
Total:     4641643
Max_count: 284
```

Output from kat_comp:
```
K-mer statistics for: 
 - Hash 1: "../EcoliK12.fasta"
 - Hash 2: "../EcoliK12.fasta"

Total K-mers in: 
 - Hash 1: 4641643
 - Hash 2: 4641643

Distinct K-mers in:
 - Hash 1: 490389
 - Hash 2: 490389

Total K-mers only found in:
 - Hash 1: 0
 - Hash 2: 0

Distinct K-mers only found in:
 - Hash 1: 0
 - Hash 2: 0

Shared K-mers:
 - Total shared found in hash 1: 4641643
 - Total shared found in hash 2: 4641643
 - Distinct shared K-mers: 490389
```

I also tried with 15-mers and 21-mers and get consistent results.  I'll have a bit of a think about this... at the moment the only explanation I can think of is that jellyfish V2.2.4 counts k-mers differently from V2.2.0, although that would be a big surprise if true.

**Comment by maplesond** [comment] 2017-03-28 08:48
Just tried jellyfish v2.2.6 and get this:
```
Unique:    40625
Distinct:  490389
Total:     4641643
Max_count: 284
```

So it doesn't appear to be a version issue.

**Comment by maplesond** [comment] 2018-04-11 10:44
I'm going to close this issue as I was unable to reproduce... feel free to reopen if this is still a problem with the latest release.

**Closed by maplesond** 2018-04-11 10:44 UTC
