### ISSUE TITLE
gcp plot as .ps/.pdf

### ISSUE THREAD

**Issue by thackl** [TGAC/KAT#14] opened 2015-10-02 16:19 UTC
Is it possible to get the `kat gcp` plot as .ps/.pdf? I tried to use `kat plot` but failed to load the kat-gcp.mx matrix.

**Comment by maplesond** [comment] 2015-10-02 16:25
Theorectically yes, but I haven't tried it with the current version.  My gnuplot configuration on my current machine only supports PNG output so that's all I've tried.  If you have correctly configured gnuplot to handle PS / PDF then you can set this with the outputtype option.

**Comment by maplesond** [comment] 2015-10-02 16:28
Ah sorry, you mean directly through kat gcp?  In that case no, we default in the code to write out PNG.  As mentioned in the previous post, it should directly through the plotting tool.  What kind of error are you receiving when trying to load the matrix file?  Does it work with PNG output?

**Comment by thackl** [comment] 2015-10-02 16:39
``` bash
~/software/kat/bin/kat plot spectra-mx -p png kat-gcp.mx
Kmer Analysis Toolkit (KAT) V2.0.6


gnuplot> set output ""
                      ^
         cannot open file; output not changed
         line 0: util.c: No such file or directory

plot_spectra_mx.cc(132): Throw in function bool kat::PlotSpectraMx::plot()
Dynamic exception type: boost::exception_detail::clone_impl<PlotSpectraMxException>
std::exception::what: std::exception
[PlotSpectraMxError*] = Error: not sure how to process matrix.  You did not select a list of content from the matrix ("--list"), or alternatively select intersection mode ("--intersection")
[1]    24575 exit 4     ~/software/kat/bin/kat plot spectra-mx -p png kat-gcp.mx
```

Are the matrices of gcp and comp compatible at all? I have not yet used comp...

However, as far as I'm concerned, I already found a quick and dirty work around based on your previous comment (added `pd.setOutputType("ps")` to `kat::Gcp::plot()`). So thanks and feel free to close this issue :)

**Comment by maplesond** [comment] 2015-10-05 10:07
Yes, that workaround would work.  So the error you were running into is caused by two things.  First I didn't set the "--output" option to be required on the plotting tools.  Setting that should fix the issue.  Second, you should probably use the "kat plot density" tool for handling GCP matrix output.

I've just updated the develop branch, to do the following:

1. updated plot README to suggest which plotting tool to use for GCP output.
2. made --output option in all plotting tools required
3. added options to GCP, HIST, COMP subtools to enable user to set the output format for plotting. 

Hope that fixes the issue.  Closing case.  Feel free to reopen if you have any further comments or suggestions.

**Comment by thackl** [comment] 2015-10-07 11:58
Almost there :). I tested it today, switching output format works. However, the --output requirement check seems to come to early blocking --help.

```
~/software/kat/bin/kat plot spectra-hist --help
# '--output' is required but missing
~/software/kat/bin/kat plot spectra-hist --output foo --help
# help screen
```

**Comment by maplesond** [comment] 2015-10-07 12:10
Ahh, yes that would be why I didn't apply the ->required() setting in the first place.  I'll write some manual checks that apply after the help option is detected.

Thanks for pointing this out.

**Comment by maplesond** [comment] 2015-10-07 14:49
Moved the output file check until after help option is checked.  Closing ticket.

**Closed by maplesond** 2015-10-07 14:49 UTC
