### ISSUE TITLE
problems when running KAT in COMP mode

### ISSUE THREAD

**Issue by jpflorido** [TGAC/KAT#48] opened 2016-06-20 11:22 UTC
Dear developers,
I'm trying to run KAT COMP using the outputs of jellyfish count and the following error comes up:
Kmer Analysis Toolkit (KAT) V2.1.0
## Running KAT in COMP mode

Loading hashes into memory...Loading hashes into memory...Loading hashes into memory...  Time taken:   Time taken: 0.00.0ss

../deps/seqan-library-2.0.0/include/seqan/basic/basic_exception.h:../deps/seqan-library-2.0.0/include/seqan/basic/basic_exception.h:368 FAILED!  (Uncaught exception of type boost::exception_detail::clone_implkat::JellyfishException: std::exception)

I've installed the latest version of KAT and all dependencies. I assume that it is not a memory problem, since jellyfish run well and KAT says that the hashes have been loaded into memory. Any ideas?
Thanks,
Javier

**Comment by maplesond** [comment] 2016-06-20 14:54
Hi Javier,
Just wondering which version of KAT you are using.  If you haven't already can you compile and test the develop version?
Dan

**Comment by jpflorido** [comment] 2016-06-21 08:42
First, I cloned stable version  V2.1.0 from Github. Then, I've tried dev version, but now another problem arises when running kat comp:

kat: error while loading shared libraries: libkat_jellyfish-2.0.so.2: cannot open shared object file: No such file or directory

Thanks!
Javier

**Comment by maplesond** [comment] 2016-06-21 12:54
I've just created a new release: https://github.com/TGAC/KAT/releases/tag/Release-2.1.0

You could try downloading and installing from this tarball.  However, I can't replicate your problem so it might help to know a bit more about your system.  Which platform are you running on?  While I've done some testing on Mac, I haven't done any for windows.  It should work ok for linux however.  Also during compilation and installation can you check the logs and see if there were any errors hidden away?  Finally, if you could let me know how you configured the software and are managing the external dependencies: boost and optionally python that might be helpful to diagnose the cause too.

Thanks,
Dan

**Comment by jpflorido** [comment] 2016-06-24 09:41
Thanks Dan,
Sorry for my late reply. I've installed the new release, but the problem remains with kat comp:

My OS is Linux Mint 17 Qiana. It seems that it is a problem related to boost library. Here you are the list of boost-related packages. Maybe, I'm missing something:

libboost-all-dev				install
libboost-atomic-dev:amd64			install
libboost-atomic1.54-dev:amd64			install
libboost-atomic1.54.0:amd64			install
libboost-chrono-dev:amd64			install
libboost-chrono1.54-dev:amd64			install
libboost-chrono1.54.0:amd64			install
libboost-chrono1.55.0:amd64			install
libboost-context-dev:amd64			install
libboost-context1.54-dev:amd64			install
libboost-context1.54.0:amd64			install
libboost-coroutine-dev				install
libboost-coroutine1.54-dev			install
libboost-date-time-dev:amd64			install
libboost-date-time1.54-dev:amd64		install
libboost-date-time1.54.0:amd64			install
libboost-dev					install
libboost-exception-dev:amd64			install
libboost-exception1.54-dev:amd64		install
libboost-filesystem-dev:amd64			install
libboost-filesystem1.54-dev:amd64		install
libboost-filesystem1.54.0:amd64			install
libboost-filesystem1.55.0:amd64			install
libboost-graph-dev:amd64			install
libboost-graph-parallel-dev			install
libboost-graph-parallel1.54-dev			install
libboost-graph-parallel1.54.0			install
libboost-graph1.54-dev:amd64			install
libboost-graph1.54.0:amd64			install
libboost-iostreams-dev:amd64			install
libboost-iostreams1.54-dev:amd64		install
libboost-iostreams1.54.0:amd64			install
libboost-locale-dev:amd64			install
libboost-locale1.54-dev:amd64			install
libboost-locale1.54.0:amd64			install
libboost-log-dev				install
libboost-log1.54-dev				install
libboost-log1.54.0				install
libboost-math-dev:amd64				install
libboost-math1.54-dev:amd64			install
libboost-math1.54.0:amd64			install
libboost-mpi-dev				install
libboost-mpi-python-dev				install
libboost-mpi-python1.54-dev			install
libboost-mpi-python1.54.0			install
libboost-mpi1.54-dev				install
libboost-mpi1.54.0				install
libboost-program-options-dev:amd64		install
libboost-program-options1.54-dev:amd64		install
libboost-program-options1.54.0:amd64		install
libboost-program-options1.55.0:amd64		install
libboost-python-dev				install
libboost-python1.54-dev:amd64			install
libboost-python1.54.0:amd64			install
libboost-random-dev:amd64			install
libboost-random1.54-dev:amd64			install
libboost-random1.54.0:amd64			install
libboost-regex-dev:amd64			install
libboost-regex1.54-dev:amd64			install
libboost-regex1.54.0:amd64			install
libboost-serialization-dev:amd64		install
libboost-serialization1.54-dev:amd64		install
libboost-serialization1.54.0:amd64		install
libboost-signals-dev:amd64			install
libboost-signals1.54-dev:amd64			install
libboost-signals1.54.0:amd64			install
libboost-system-dev:amd64			install
libboost-system1.54-dev:amd64			install
libboost-system1.54.0:amd64			install
libboost-system1.55.0:amd64			install
libboost-test-dev:amd64				install
libboost-test1.54-dev:amd64			install
libboost-test1.54.0:amd64			install
libboost-thread-dev:amd64			install
libboost-thread1.54-dev:amd64			install
libboost-thread1.54.0:amd64			install
libboost-timer-dev:amd64			install
libboost-timer1.54-dev:amd64			install
libboost-timer1.54.0:amd64			install
libboost-timer1.55.0:amd64			install
libboost-tools-dev				install
libboost-wave-dev:amd64				install
libboost-wave1.54-dev:amd64			install
libboost-wave1.54.0:amd64			install
libboost1.54-dev				install
libboost1.54-tools-dev				install

And python-boost related packages:
libboost-mpi-python-dev				install
libboost-mpi-python1.54-dev			install
libboost-mpi-python1.54.0			install
libboost-python-dev				install
libboost-python1.54-dev:amd64			install
libboost-python1.54.0:amd64	


Is something missing?
Thanks,
Javier

**Comment by maplesond** [comment] 2016-06-24 10:01
Hi Javier,

I'm also running Mint so that shouldn't be the issue.  Your boost installation looks complete, so I don't think that's the problem either.  Just to check, is this a system install of boost, though apt-get?  Or a custom build?  It shouldn't make a difference but one thing to try is to download boost and build the packages you need.  See [https://github.com/TGAC/KAT/blob/master/.travis/install.sh](url) for an example of how to do this:

`wget -q http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz/download`
`mv download boost.tar.gz`
`tar -xf boost.tar.gz`
`cd boost_1_59_0`
`sudo ./bootstrap.sh --with-libraries=chrono,timer,program_options,filesystem,system`
`sudo ./b2 -d0 install` 
`cd ..`

That will take a few minutes to compile, then when you run the KAT configure script use "--with-boost=<path_to_boost>"?  

Also can you tell me the commands you used for the result of the compilation process?  One thing I've just noticed in the current release is that sometimes KAT doesn't completely install correctly using "make install" unless you first run "make man".  This is a bug I need to fix as the manual should be automatically build if python and sphinx-doc are present, or ignored if not.

Hope this helps.

**Comment by jpflorido** [comment] 2016-06-24 10:45
Thanks Dan,
I've installed boost as you suggested, but, what is the exact command for configure script including --with-boost? ./configure --with-boost=/usr/local/include/boost/ or ./configure --with-boost=/usr/local/lib?

Thanks again,
Javier

**Comment by maplesond** [comment] 2016-06-24 10:51
Sorry my mistake.  After running the `./b2 install` command you shouldn't need the `--with-boost` option as it will get installed to your system.  If you like you could try using `--with-boost=<path_to_boost_build>`.  I think normally the local build will be in a `build` directory, containing `include` and `lib` subdirectories.  Either way, it shouldn't make any difference though.

**Comment by jpflorido** [comment] 2016-06-24 14:53
Thanks Dan,
Once boost has been installed, I've tried again and another error comes up in KAT comp :

Kmer Analysis Toolkit (KAT) V2.1.0

kat.cc(91): Throw in function Mode parseMode(std::string)
Dynamic exception type: boost::exception_detail::clone_impl<KatException>
std::exception::what: std::exception
[KatError*] = Could not recognise mode string: comt

This is different from the first one. At least, we made some progress! :-)

**Comment by maplesond** [comment] 2016-06-24 14:57
Can you show me the command line you used?  Looks like a typo: `comt` instead of `comp`.

**Comment by bjclavijo** [comment] 2016-06-24 14:57
This is a rather easy one, try "kat comp" instead of "kat comt"...

**Comment by jpflorido** [comment] 2016-06-24 15:01
Yes, you were right, sorry....it is comp,we come back to the original error :

Loading hashes into memory...Loading hashes into memory...  Time taken: 0.0s

../deps/seqan-library-2.0.0/include/seqan/basic/basic_exception.h:368 FAILED!  (Uncaught exception of type boost::exception_detail::clone_impl<kat::JellyfishException>: std::exception)
Aborted

**Comment by maplesond** [comment] 2016-06-24 15:04
Unsure about this one, can you post your command line?  Also what input files are you using?  I'm wondering if you are trying to load jellyfish hashes from a difference, incompatible, version of jellyfish.

**Comment by maplesond** [comment] 2016-11-04 14:47
There hasn't been any activity in this issue for a while, so I'm closing it.  I also haven't been able to reproduce this problem, so hopefully it doesn't exist in the most recent version of KAT.  Feel free to reopen if there is still a problem.

**Closed by maplesond** 2016-11-04 14:47 UTC
