### ISSUE TITLE
KAT filter seq string error

### ISSUE THREAD

**Issue by webbchen** [TGAC/KAT#76] opened 2017-02-13 12:19 UTC
Hello

When filtering paired-end reads  using a kmer matrix generated from the same library KAT filter seq runs for a bit and the exits as follows:
$ kat filter seq -t 48 -m 71 -s --stats -o 4-P_brassicae71_seqfilter_paired --seq mysample_R1_001.fastq --seq2 mysample_R2_001.fastq mysample71_kmerfilter_both-in.jf71 

Kmer Analysis Toolkit (KAT) V2.3.1

Running KAT in filter sequence mode
-----------------------------------

Loading hashes into memory... done.  Time taken: 12.5s

Filtering sequences ...
  Time taken: 0.0s

KAT filter seq completed.
Total runtime: 12.6s

Error: basic_string::substr: __pos (which is 45) > this->size() (which is 44)

It starts to write to the four expected output files which are left with between 14 and 20 reads in each.
I tried filtering just the forward reads with a matrix generated from the forward reads and the issue appears there, too. 

Many thanks and kind regards,

Anne

**Comment by maplesond** [comment] 2018-01-31 09:30
Hi Anne,

Sorry for not getting back to you on this.  It looks like this is an issue caused by the kmer size being larger than the string to analyse size.  Are you using trimmed reads?

I'm currently working on a new version of KAT.  I'll fix this issue in the upcoming version.
Best, Dan

**Comment by webbchen** [comment] 2018-01-31 12:40
Hi Dan

Thanks for coming back about this. I'm using trimmed reads, yes. I haven't done anything else with that particular module of KAT since reporting the error.

Kind regards,

Anne

**Comment by maplesond** [comment] 2018-01-31 12:48
Hi Anne,
I've pushed what I think should be a fix for this to the develop branch.  In case you want to test this please note there is a slightly different install procedure compared to the last version, so take a look at the steps in the README.md file.
Best regards,
Dan

**Comment by maplesond** [comment] 2018-04-11 10:44
Fixed in latest release

**Closed by maplesond** 2018-04-11 10:44 UTC
