### ISSUE TITLE
KAT cannot import numpy in Singularity container

### ISSUE THREAD

**Issue by bmichanderson** [TGAC/KAT#119] opened 2018-11-29 13:06 UTC
I'm building my first Singularity container to run KAT on a supercomputer (I'm also new to GitHub, so pardon my formatting).
After multiple refinements, I can get it to run, but it fails when I try to use plotting scripts, with the error (partial):

Traceback (most recent call last):
  File "//usr/local/share/kat/scripts/kat/plot/spectra_hist.py", line 6, in <module>
    from misc import *
  File "/usr/local/share/kat/scripts/kat/plot/misc.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

When I run python in the container, it has no problem importing numpy.
singularity exec kat.img python3
import numpy

I'll paste my Singularity recipe below:
# 
Bootstrap: docker
From: ubuntu:18.04

%labels
	# This section contains labels for the container
	MAINTAINER bmichanderson

%post
	# This section is executed after the base OS has been created
	# Upgrade software and install essentials for building KAT
	apt update
	apt -y upgrade
	apt install -y build-essential make autoconf automake libtool libpthread-stubs0-dev \
			zlib1g zlib1g-dev wget software-properties-common git
	
	# Install python packages
	apt-add-repository universe
	apt update
	apt -y upgrade
	apt install -y python3.6 python3-pip
	pip3 install setuptools tabulate scipy numpy matplotlib sphinx
	
	# Install KAT
	# NOTE: the following lines were my first attempt, but it seems like v2.4.1
	# has a problem with installing the python scripts or correctly locating them.
	#VERSION="2.4.1"
	#URL=https://github.com/TGAC/KAT/archive/Release-"$VERSION".tar.gz
	#wget "$URL"
	#tar -xzf Release-"$VERSION".tar.gz
	#cd KAT-Release-"$VERSION"
	git clone https://github.com/TGAC/KAT.git
	cd KAT
	./build_boost.sh
	./autogen.sh
	./configure
	# can leverage extra cores with the -j option
	make -j6
	make install

	# test that the program works
	kat --version

**Comment by maplesond** [comment] 2018-11-29 13:44
Hi @bmichanderson, you're probably better off using the KAT singularity container I've already put in singularity hub: https://www.singularity-hub.org/collections/1739

Hope that helps,
Dan

**Comment by maplesond** [comment] 2018-11-29 13:53
Looking at the two recipes I can't see much of a difference, so I'm not sure what is specifically causing the issue you are seeing.  Let me know if my one fixes the issue.  Another option is to try docker container.  See the Dockerfile, in the root of the repo.  Try building and testing that.  If it works, it should be easy to wrap that in a singularity container.  If not I'll try and figure out what's causing the issue.

**Comment by bmichanderson** [comment] 2018-11-29 14:38
Hi Dan,
Thanks for the quick response. I downloaded your singularity recipe and built the container on my machine and I get the same error. Here is precisely what I run:

>singularity exec kat.img kat plot spectra-hist

Complete output:

Kmer Analysis Toolkit (KAT) V2.4.2

Traceback (most recent call last):
  File "//usr/local/share/kat/scripts/kat/plot/spectra_hist.py", line 6, in <module>
    from misc import *
  File "/usr/local/share/kat/scripts/kat/plot/misc.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//usr/local/share/kat/scripts/kat/plot/spectra_hist.py", line 8, in <module>
    from kat.plot.misc import *
  File "//usr/local/share/kat/scripts/kat/plot/misc.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
../lib/include/kat/pyhelper.hpp(159): Throw in function void kat::PyHelper::execute(std::__cxx11::string, int, char**)
Dynamic exception type: boost::exception_detail::clone_impl<kat::KatPythonException>
std::exception::what: std::exception
[kat::KatPythonError*] = Unexpected python error


I've not used Docker before, but I might look into that.
Cheers,
Ben

**Comment by bmichanderson** [comment] 2018-11-29 15:51
Hi Dan,

Just an update that the same error appears using the Dockerfile.
I downloaded the Dockerfile, installed DockerCE, built the container (tagged kat) and ran it with:
>sudo docker run kat kat plot spectra-hist

This produced the same error as above.

Cheers,
Ben

**Comment by maplesond** [comment] 2018-11-29 16:33
Ok thanks Ben.  Sounds like something I need to investigate.  I'll get back to you when I have a solution.

**Comment by maplesond** [comment] 2018-11-30 08:47
Hi Ben, I can reproduce the problem.  Interestingly, you can still run the python scripts directly: e.g.: executed in the docker or singularity container: `/KAT/scripts/kat/plot/spectra_hist.py`.  This seems to pick up numpy correctly.  It's only when called through the KAT C++ binary that there is an issue.  I'll work on getting a fix for this.

**Comment by bmichanderson** [comment] 2018-12-07 16:43
Hi Dan, here's another update. I have changed my Singularity recipe so that rather than using pip3 to install the python packages, it uses apt. I'm not very familiar with how that would make a difference, but it seems to be working now. You can find the recipe in my repository: https://github.com/bmichanderson/singularity-containers

Might the binary be calling 'python' instead of 'python3' (?), and somehow apt sets the environment up so this works as intended?

**Comment by maplesond** [comment] 2018-12-09 17:49
Looks like it fixes the issue for me too.  Thanks!  I've created a new dockerfile and a new singularity file which uses the rocker hub image on the develop branch.

**Closed** 2018-12-10 11:09 UTC
