### ISSUE TITLE
Makefile: spaces instead of tabs

### ISSUE THREAD

**Issue by thackl** [TGAC/KAT#13] opened 2015-10-02 15:08 UTC
I just tried to make KAT from the latest pull. After 
``` bash
./configure --prefix=$HOME/software/kat --with-boost=$HOME/software/boost;
make
```
I ran into `Makefile:918: *** missing separator.  Stop`. Looks like you caught some leading spaces in `install-data-hook:` and `uninstall-local:` section.

**Comment by maplesond** [comment] 2015-10-02 15:22
Did you pull the latest and run ./autogen.sh, prior to ./configure?  I'm not sure why you would run into this otherwise as I haven't updated the Makefile.am since V2.0.1.

If this doesn't work, either try a clone from the repo, or download the distributable from here: https://github.com/TGAC/KAT/releases/download/Release-2.0.6/kat-2.0.6.tar.gz

**Comment by thackl** [comment] 2015-10-02 15:28
Actually I cloned (c19ab3a - Finish Release-2.0.6), ran ./autogen.sh and ./configure... I manually replaced the spaces by tab and everything worked. Just wanted to let you know...

**Comment by maplesond** [comment] 2015-10-02 15:33
Ok, thanks for this.  What platform are you running?  I'll try and reproduce on my system and fix.  I'll leave the ticket open until it's done.

**Comment by thackl** [comment] 2015-10-02 15:40
openSUSE 12.3, GNU Make 3.82.

I think it should be enough to replace the 4 spaces in Makefile.am before the `install-data-hook:` and `uninstall-local:` recipes by tabs...

**Comment by maplesond** [comment] 2015-10-02 15:57
I've updated the develop branch with the changes.  I can't seem to reproduce on my system, so if you could let me know whether the new changes work I'll make sure they get into the next official version.  Thanks again for letting me know about this.

**Comment by thackl** [comment] 2015-10-02 16:05
Works like a charm...

**Comment by maplesond** [comment] 2015-10-02 16:06
Wonderful.  Thanks again.  This change will be in the next release.  Closing ticket.

**Closed by maplesond** 2015-10-02 16:06 UTC
